migration to DSL2
nf-core/smrnaseq pull request #104
Opened 2021-09-09 22:04 UTC by lpantano

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md)
    - [X] If necessary, also make a PR on the nf-core/smrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2021-11-04 12:26 UTC, JoseEspinosa requested changes
Huge work, very nice! :smile: 
Most of my comments are related to the new way of reporting versions, although there are some others related to more general stuff.
Also, I was wondering whether some of the local modules (e.g. bowtie/build and bowtie/align) could not be used from nf-core modules instead, but might be that I am not aware of all the details and that it is not possible to use them in this pipeline.
Almost there :rocket:

2021-11-04 12:26 UTC, JoseEspinosa commented on subworkflows/local/mirdeep2.nf
> +    MIRDEEP2_PIGZ ( reads )
If the modules are split in three files get version for each module

2021-11-04 12:26 UTC, JoseEspinosa commented on subworkflows/local/mirna_quant.nf
> +    SEQCLUSTER_SEQUENCES ( reads_seqcluster ).collapsed.set { reads_collapsed }
Emit version for each module and emit a `ch_versions` with all of them

2021-11-04 12:26 UTC, JoseEspinosa commented on subworkflows/local/mirtrace.nf
> +    versions   = MIRTRACE_RUN.out.versions
Update with new syntax

2021-11-04 12:26 UTC, JoseEspinosa commented on subworkflows/nf-core/fastqc_trimgalore.nf
> +include { TRIMGALORE       } from '../../modules/local/trimgalore'                      addParams( options: params.trimgalore_options )
Update if the nf-core module can be used

2021-11-04 12:26 UTC, JoseEspinosa commented on workflows/smrnaseq.nf
> +WorkflowSmrnaseq.initialise(params, log)
Now the validation of the parameters is not included in the library file, see my comment on the corresponding file

2021-11-04 12:26 UTC, JoseEspinosa commented on workflows/smrnaseq.nf
> +bt_index = params.bt_indices ?: bt_index_from_species
Maybe you could format the file this way? I think I had too much influence from @drpatelh :smile: 
```suggestion
bt_index_from_species = params.genome ? params.genomes[ params.genome ].bowtie ?: false : false
bt_index              = params.bt_indices ?: bt_index_from_species
```

2021-11-04 12:26 UTC, JoseEspinosa commented on workflows/smrnaseq.nf
> +    )
Change this with the new implementation, once all the versions are reported by modules and subworkflow, see [here](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/workflows/rnaseq.nf#L755-L757)
```suggestion
```

2021-11-04 12:26 UTC, JoseEspinosa commented on workflows/smrnaseq.nf
> +    ch_software_versions = ch_software_versions.mix(MULTIQC.out.versions.ifEmpty(null))
You may need to add `CUSTOM_DUMPSOFTWAREVERSIONS` output as input, either as a channel such as in `rnaseq` [pipeline](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/workflows/rnaseq.nf#L769) or by mixing it with `ch_mulitqc_files` as is done here
```suggestion
```

2021-11-04 12:26 UTC, JoseEspinosa commented on nextflow.config
> +    outdir                     = './results'
This is also declared in "boilerplate options"
```suggestion
```

2021-11-04 12:26 UTC, JoseEspinosa commented on nextflow.config
> +    save_reference             = true
Shouldn't be this by default set to false instead?
```suggestion
    save_reference             = false
```

2021-11-04 13:22 UTC, FriederikeHanssen requested changes
Great work!! 🚀 Just a couple of minor things, mostly regarding versioning (which I see now also Jose has reviewed already). I think adding the citations would be fairly important too.

2021-11-04 13:22 UTC, FriederikeHanssen commented on main.nf
> +// /*
all of this can be removed right? Or is there a reason to keep it?

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/bowtie_genome.nf
> +include { saveFiles; initOptions; getSoftwareName } from './functions'
Is the nf-core/modules bowtie module an option?

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/bowtie_map_mirna.nf
> +    def software = getSoftwareName(task.process)
This is not used anymore afaik

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/bowtie_map_mirna.nf
> +    bowtie --version 2>&1 | head -1 | sed 's/^.*version //' > ${software}.version.txt
Versions are now colected as yml. maybe take a look at some of the nf-core/modules on how its done

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/format_fasta_mirna.nf
> +    // publishDir "${params.outdir}",
Why is this commented out? Shouldn't be necessary but you can set whether something is published or not in the modules.config.

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/mirdeep2.nf
> +// Import generic module functions
I think it would be nice to stick with the structure of one module per file and then combin the modules into subworkflows

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/mirtop_quant.nf
> +// Import generic module functions
same as for mirdeep2

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/seqcluster_collapse.nf
> +    // publishDir "${params.outdir}",
same as above

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/local/trimgalore.nf
> +process TRIMGALORE {
There is a nf-core/module trimgalore. is that usable for you?

2021-11-04 13:22 UTC, FriederikeHanssen commented on modules/nf-core/modules/samtools/view/main.nf
> +// Import generic module functions
Some of the samtools modules (including this one) have recently been updated. Might be worth to run the modules update command before release

2021-11-04 13:22 UTC, FriederikeHanssen commented on subworkflows/local/mirna_quant.nf
> +include {   PARSE_FASTA_MIRNA  as PARSE_MATURE
Maybe align for readability

2021-11-04 13:22 UTC, FriederikeHanssen commented on subworkflows/local/mirna_quant.nf
> +    emit:
align by `=` sign

2021-11-05 08:19 UTC, apeltzer commented
I will wait until Joses / Frederikes requests are accepted / discussed & then have a look afterwards - please ping me then here directly or via Slack 👍🏻

2021-11-05 20:53 UTC, lpantano commented
Thanks @apeltzer.
@JoseEspinosa @FriederikeHanssen  I tried to adapt all the comments not related to version. 

Some modules are local even if nf-core has similar modules because there is something unique to smrnaseq and it would take some evaluation to do the adaptation.

I am leaving the versioning, so @JoseEspinosa can make the first change to use the YAML format, and I can then modify all the local modules to that format as well. 

The plan was to merge, and the @JoseEspinosa will make another PR with the versioning and I will work on top of that. I hope that is ok for everybody else.

As well, there is a final module to add, but I need to do the docker containers, so I am skipping it here. (EDGER module in mirna_quant.nf)

Thanks!

2021-11-08 09:29 UTC, JoseEspinosa approved these changes
I think most of the changes have been addressed apart from the implementation of the new versioning. Thanks @lpantano ! :rocket: 
I will merge this PR and work on the versioning on top of them as we agreed.
Also, I will close https://github.com/nf-core/smrnaseq/pull/101 since we are addressing the merging of the new nf-core template on this PR.

2021-11-08 09:40 UTC, FriederikeHanssen approved these changes
Looks good :) Great work 🥳 , and as discussed remaining things can go on top of the versioning PR

2021-11-08 09:40 UTC, FriederikeHanssen commented on modules/local/format_fasta_mirna.nf
> +options        = initOptions(params.options)
Commit this?

2021-11-08 09:41 UTC, merged