PR for 2.0.0
nf-core/smrnaseq pull request #151
Opened 2022-05-19 10:04 UTC by apeltzer

## PR checklist for 2.0.0 (opening this on behalf of the smrnaseq team 🥳 

Mostly so that we can all have a final round of review to get things done asap. 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
    - [x] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/smrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint .`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2022-05-20 15:26 UTC, JoseEspinosa requested changes
Awesome job! 🚀 
Mainly small suggestion.
I also realized that local modules are not using `ext.args` to pass the arguments might be worth implementing it so that users can change the parameters given to a tool, but this might also be implemented on a new release along with `mirgenedb`

2022-05-20 15:26 UTC, JoseEspinosa commented on nextflow_schema.json
> +                "bt_indices": {
Would it be more self-explanatory just `bowtie_index`?

2022-05-20 15:26 UTC, JoseEspinosa commented on nextflow_schema.json
> +                "bt_indices": {
If yes, all the instances where the parameter is used should be changed.

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/local/mirdeep2.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/local/genome_quant.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/local/mirna_quant.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/local/mirtrace.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/nf-core/bam_sort_samtools.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/nf-core/bam_stats_samtools.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on subworkflows/nf-core/fastqc_trimgalore.nf
> +
```suggestion
```

2022-05-20 15:26 UTC, JoseEspinosa commented on workflows/smrnaseq.nf
> +
```suggestion
```

2022-05-30 11:12 UTC, apeltzer commented on modules/local/mirdeep2_mapper.nf
> +    -o 4
Hmm fair point!

2022-05-30 11:16 UTC, apeltzer commented
Agree with @JoseEspinosa that we could/should probably add the `ext.args` possibility toallow for more flexibility but this could be done in the next release (2.1.0) also integrating mirgenedb + contamination filtering possibilities in one go. Regarding renaming of the bt_index channel, I agree this could be a favourable thing to have so I'm going to change that to be a bit more explicit.

2022-05-30 21:06 UTC, JoseEspinosa approved these changes
Thanks @apeltzer LGTM! 😄
Created this small one to fix the linting: https://github.com/nf-core/smrnaseq/pull/157

2022-05-31 15:39 UTC, sguizard approved these changes
Apart no default value for `--outdir`, LGMT!

2022-05-31 19:18 UTC, merged