Merge-template-2.9
nf-core/smrnaseq pull request #272
Opened 2023-08-30 06:57 UTC by apeltzer

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/smrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-08-30 07:42 UTC, grst requested changes
Found a couple of minor things

2023-08-30 07:42 UTC, grst commented on README.md
> -
Would be good to actually show how the samplesheet needs to look like

2023-08-30 07:42 UTC, grst commented on README.md
>     -profile <docker/singularity/.../institute> \
something's wrong with the indentation in the next lines

2023-08-30 07:42 UTC, grst commented on nextflow.config
> +    validate_params                  = true
```suggestion
```

(duplication...)

2023-08-30 07:42 UTC, grst commented on nextflow.config
> +    version = '2.2.1dev'
Shouldn't this be `2.3dev` of `2.2.2dev` as `2.2.1` is already released?

2023-08-30 07:55 UTC, grst approved these changes
LGTM now!

2023-08-30 10:52 UTC, christopher-mohr reviewed
As just discussed LGTM, we just need to adapt to the new `samtools` subworkflows.

2023-08-30 14:18 UTC, christopher-mohr commented on subworkflows/local/mirna_quant.nf
> +include {   BAM_SORT_STATS_SAMTOOLS as BAM_STATS_MATURE
The second argument of these calls below needs to be a map like `[meta, fasta]. Maybe the easiest solution would be to also adapt the module `format_fasta_mirna` to also accept and return a map of `[meta, fasta]`.

2023-09-01 11:39 UTC, christopher-mohr approved these changes
One comment, apart from that LGTM!

2023-09-01 11:39 UTC, christopher-mohr commented on workflows/smrnaseq.nf
> +        file(params.input)
Shouldn't this still be `ch_input` ?

2023-09-01 12:31 UTC, merged