Release PR for 2.2.2 Patch Release
nf-core/smrnaseq pull request #277
Opened 2023-09-01 15:46 UTC by apeltzer

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/smrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-09-01 17:18 UTC, jfy133 reviewed
Mostly changelog and versions look weird for a release pr

2023-09-01 17:18 UTC, jfy133 commented on CHANGELOG.md
> +## dev
Jumping ahead if this is a patch release?

2023-09-01 17:18 UTC, jfy133 commented on assets/multiqc_config.yml
> +  This report has been generated by the <a href="https://github.com/nf-core/smrnaseq/2.2.2dev" target="_blank">nf-core/smrnaseq</a>
Wouldn't this be e.g. 2.2.3?

2023-09-01 17:18 UTC, jfy133 commented on modules/local/parse_fasta_mirna.nf
> +    tuple val(meta2), path(fasta)
Why meta2 given its the only input channel?

2023-09-01 17:18 UTC, jfy133 commented on CHANGELOG.md
> +## dev
Missing version bumps for multiQC and fasto for example

2023-09-01 17:18 UTC, jfy133 commented on CHANGELOG.md
> +## dev
Missing updates to paths for one of the tools (and removing .gz)

2023-09-04 06:25 UTC, christopher-mohr requested changes
Just some minor things in addition to what James already pointed out.

2023-09-04 06:25 UTC, christopher-mohr commented on CHANGELOG.md
> +## [v2.2.2](https://github.com/nf-core/smrnaseq/releases/tag/2.2.2) - 2023-06-01
Correct release date?

2023-09-04 06:25 UTC, christopher-mohr commented on assets/multiqc_config.yml
> +  This report has been generated by the <a href="https://github.com/nf-core/smrnaseq/2.2.2dev" target="_blank">nf-core/smrnaseq</a>
Or just `2.2.2` ?

2023-09-04 06:25 UTC, christopher-mohr commented on nextflow.config
> +    version = '2.2.2dev'
```suggestion
    version = '2.2.2'
```

2023-09-04 06:25 UTC, christopher-mohr commented on subworkflows/local/genome_quant.nf
> +    fasta //channel: [ val(meta2), [ reads ] ]
I think this is just `fasta` here without meta.

 ```suggestion
    fasta 
```

2023-09-04 06:50 UTC, grst approved these changes
Nothing to add besides what has been said. 
As the last release was 2.2.1 this one should be 2.2.2 or 2.3.0

2023-09-04 07:31 UTC, maxulysse commented on CHANGELOG.md
> +- Remove public_aws_ecr profile
This should be in the release

2023-09-05 06:16 UTC, christopher-mohr approved these changes
One comment, LGTM besides that.

2023-09-05 06:16 UTC, christopher-mohr commented on subworkflows/local/genome_quant.nf
> +   fasta
Not sure if the identation is wrong here?

2023-09-05 09:15 UTC, merged